/* C application - generated by Brief */
/* Target: Kernel Module */

#include <linux/module.h>
#include <linux/kernel.h>
#include <linux/kthread.h>
#include <linux/delay.h>

typedef struct {
    bool gpu_bar_mapped;
    bool dma_active;
    uint32_t current_layer;
    uint32_t MAX_LAYERS;
} State;

static State state_instance;
static State *state = &state_instance;

void state_init(void) {
    state->gpu_bar_mapped = false;
    state->dma_active = false;
    state->current_layer = 0;
    state->MAX_LAYERS = 0;
}

bool init(void) {
    /* pre: Eq(Identifier("gpu_bar_mapped"), Bool(false)) */
    state->gpu_bar_mapped = true;
    /* transaction complete */
    /* post: Eq(Identifier("gpu_bar_mapped"), Bool(true)) */
    return true;
}

bool calc_layer(void) {
    /* pre: And(Not(Identifier("dma_active")), Lt(Identifier("current_layer"), Identifier("MAX_LAYERS"))) */
    state->current_layer = (state->current_layer + 1);
    /* transaction complete */
    /* post: Eq(Identifier("current_layer"), Add(PriorState("current_layer"), Integer(1))) */
    return true;
}

bool stream_layer(void) {
    /* pre: And(Identifier("dma_active"), Gt(Identifier("current_layer"), Integer(0))) */
    state->dma_active = false;
    /* transaction complete */
    /* post: Eq(Identifier("dma_active"), Bool(false)) */
    return true;
}

bool cleanup(void) {
    /* pre: Bool(true) */
    /* transaction complete */
    /* post: Bool(true) */
    return true;
}

void init_wrapper(void) {
    // Static allocation for bare-metal/kernel
    state_init();
}


// Kernel module entry points
static int __init brief_init(void) {
    init();
    return 0;
}
module_init(brief_init);

static void __exit brief_exit(void) {
    cleanup();
}
module_exit(brief_exit);

MODULE_DESCRIPTION("VITRIOL: Direct NVMe to GPU Streamer for Infinite VRAM");
MODULE_LICENSE("GPL");
