#!/usr/bin/env python3
"""
VITRIOL TUI Dashboard — Textual-based terminal UI for live inference monitoring,
config management, and server control.

Usage:
  vitriol tui

Requires: textual (pip install textual)
"""

from __future__ import annotations

import os
import re
import subprocess
import time
import signal
from pathlib import Path
from typing import Optional

import configparser

from textual import work
from textual.app import App, ComposeResult
from textual.containers import Container, Horizontal, Vertical, ScrollableContainer, Grid
from textual.css.query import NoMatches
from textual.reactive import reactive
from textual.widgets import (
    Header, Footer, Static, Label, RichLog, Button, Input, Select,
    TabbedContent, TabPane, LoadingIndicator
)
from textual.screen import Screen, ModalScreen
from textual.message import Message


# ── Paths ──────────────────────────────────────────────────────

CONFIG_DIR = Path(os.environ.get("HOME", "~")) / ".vitriol"
CONFIG_PATH = CONFIG_DIR / "config"
LOG_PATH = CONFIG_DIR / "server.log"
PID_PATH = CONFIG_DIR / "server.pid"
LOGO_PATH = Path(__file__).resolve().parent.parent / "assets" / "ansi-logo.txt"
SCRIPT_PATH = Path(__file__).resolve().parent.parent / "scripts" / "vitriol"

# ── Helpers ────────────────────────────────────────────────────

def get_vram() -> tuple[float, float]:
    """Return (used_mib, total_mib) via nvidia-smi."""
    try:
        out = subprocess.check_output(
            ["nvidia-smi", "--query-gpu=memory.used,memory.total",
             "--format=csv,noheader,nounits"],
            timeout=3, text=True
        )
        parts = out.strip().split(", ")
        return float(parts[0]), float(parts[1])
    except Exception:
        return 0.0, 0.0

def load_logo() -> str:
    """Return ANSI logo as a string, or empty if not found."""
    if not LOGO_PATH.exists():
        return ""
    with open(LOGO_PATH) as f:
        lines = f.readlines()
        for line in lines:
            if "echo -e" in line or r"\033" in line:
                idx = line.find(r"\033")
                if idx >= 0:
                    return line[idx:].strip().rstrip("'").replace(r"\033", "\033").replace("'", "")
        return ""

def load_config() -> dict:
    """Parse ~/.vitriol/config into a flat dict with section.key."""
    cfg = {}
    if not CONFIG_PATH.exists():
        return cfg
    parser = configparser.ConfigParser()
    parser.read(CONFIG_PATH)
    for section in parser.sections():
        for key, val in parser[section].items():
            cfg[f"{section}.{key}"] = val
    return cfg

def save_config(flat: dict) -> None:
    """Write flat dict back to ~/.vitriol/config, preserving section structure."""
    sections = {}
    for full_key, val in flat.items():
        if "." in full_key:
            sec, key = full_key.split(".", 1)
        else:
            sec, key = "vitriol", full_key
        sections.setdefault(sec, {})[key] = val
    CONFIG_DIR.mkdir(parents=True, exist_ok=True)
    parser = configparser.ConfigParser()
    # Preserve existing order by reading first
    if CONFIG_PATH.exists():
        parser.read(CONFIG_PATH)
    # Override values
    for sec, kv in sections.items():
        if sec not in parser:
            parser[sec] = {}
        for k, v in kv.items():
            parser[sec][k] = str(v)
    with open(CONFIG_PATH, "w") as f:
        f.write("# VITRIOL Configuration\n")
        f.write("# Generated by vitriol tui\n\n")
        parser.write(f)

def is_server_running() -> bool:
    """Check if llama-server PID is alive."""
    if not PID_PATH.exists():
        return False
    try:
        pid = int(PID_PATH.read_text().strip())
        os.kill(pid, 0)
        return True
    except (ValueError, OSError, FileNotFoundError):
        return False

def stop_server() -> bool:
    """Stop running server via PID file. Returns True if stopped."""
    if not PID_PATH.exists():
        return False
    try:
        pid = int(PID_PATH.read_text().strip())
        os.kill(pid, signal.SIGTERM)
        # Wait briefly
        for _ in range(10):
            try:
                os.kill(pid, 0)
                time.sleep(0.5)
            except OSError:
                break
        PID_PATH.unlink(missing_ok=True)
        return True
    except (ValueError, OSError, FileNotFoundError):
        return False


# ── Log Parser ──────────────────────────────────────────────────

TIMING_RE = re.compile(
    r"eval time\s*=\s*([\d.]+)\s*ms\s*/\s*(\d+)\s+tokens"
)
PROMPT_RE = re.compile(
    r"prompt eval time\s*=\s*([\d.]+)\s*ms\s*/\s*(\d+)\s+tokens"
)
DRAFT_RE = re.compile(
    r"draft acceptance rate\s*=\s*([\d.]+)"
)

class ServerLogWatcher:
    """Watches server log file for new timing lines."""

    def __init__(self):
        self._pos = LOG_PATH.stat().st_size if LOG_PATH.exists() else 0
        self.last_tps: float = 0.0
        self.last_prompt_tps: float = 0.0
        self.last_acceptance: float = 0.0
        self.new_data_available = False

    def poll(self) -> None:
        if not LOG_PATH.exists():
            return
        try:
            with open(LOG_PATH, errors="replace") as f:
                f.seek(self._pos)
                new_data = f.read()
                self._pos = f.tell()

            lines = new_data.splitlines()
            if not lines:
                return

            self.new_data_available = False
            for line in lines:
                m = TIMING_RE.search(line)
                if m:
                    ms, tokens = float(m.group(1)), int(m.group(2))
                    self.last_tps = (tokens / ms) * 1000 if ms > 0 else 0.0
                    self.new_data_available = True
                m = PROMPT_RE.search(line)
                if m:
                    ms, tokens = float(m.group(1)), int(m.group(2))
                    self.last_prompt_tps = (tokens / ms) * 1000 if ms > 0 else 0.0
                    self.new_data_available = True
                m = DRAFT_RE.search(line)
                if m:
                    self.last_acceptance = float(m.group(1))
                    self.new_data_available = True
        except (IOError, PermissionError):
            pass


# ── Config Screen ──────────────────────────────────────────────

CONFIG_FIELDS = [
    ("model.path", "Model path", "Path to GGUF model file"),
    ("model.context", "Context", "Context window size"),
    ("model.threads", "Threads", "CPU threads for prompt processing"),
    ("model.ngl", "GPU Layers", "GPU layers to offload"),
    ("vitriol.mode", "VITRIOL Mode", "stream | sync | async | off"),
    ("vitriol.lru_mb", "LRU Cache (MB)", "VRAM cache (0=off, FP16 only)"),
    ("vitriol.output_cache", "Output Cache", "on | off"),
    ("vitriol.predictive_prefetch", "Predict Prefetch", "on | off"),
    ("vitriol.pin_first_n_layers", "Pin Layers", "Expert VRAM pin count"),
    ("vitriol.prune_experts", "Prune Experts", "Drop bottom N experts"),
    ("vitriol.reasoning", "Reasoning", "on | off"),
    ("spec.type", "Spec Type", "mtp | draft (empty=off)"),
    ("spec.draft_n_max", "Draft N-Max", "MTP draft count"),
    ("kv.mode", "KV Mode", "standard | offload | sparse"),
    ("kv.quant_mode", "KV Quant", "f16 | q8_0 | q4_0"),
    ("server.host", "Server Host", "Bind address"),
    ("server.port", "Server Port", "API port"),
    ("server.parallel", "Parallel", "Parallel slots"),
]

class ConfigScreen(Screen):
    """Full-screen config editor with labeled inputs."""

    BINDINGS = [("escape", "back", "Back to Dashboard")]

    def compose(self):
        yield Header()
        with ScrollableContainer():
            yield Label("VITRIOL Configuration", classes="section-title")
            yield Label("Edit values and press Save. Changes take effect on next server start.")
            self.inputs = {}
            cfg = load_config()
            for section in ["model", "vitriol", "spec", "kv", "server"]:
                yield Label(f"[{section}]", classes="section-header")
                for key, label, hint in CONFIG_FIELDS:
                    if not key.startswith(f"{section}."):
                        continue
                    k = key.split(".", 1)[1]
                    val = cfg.get(key, "")
                    yield Label(label, classes="field-label")
                    inp = Input(
                        value=val,
                        placeholder=hint,
                        id=f"cfg-{section}-{k}",
                        classes="field-input"
                    )
                    self.inputs[key] = inp
                    yield inp
        with Horizontal(classes="button-row"):
            yield Button("Save & Apply", id="save-config", variant="primary")
            yield Button("Discard", id="discard-config", variant="default")

    def on_button_pressed(self, event: Button.Pressed):
        if event.button.id == "save-config":
            new_cfg = {}
            for key, inp in self.inputs.items():
                new_cfg[key] = inp.value
            save_config(new_cfg)
            self.app.pop_screen()
            self.app.query_one("#status-msg", Static).update("Config saved")
        elif event.button.id == "discard-config":
            self.app.pop_screen()

    def action_back(self):
        self.app.pop_screen()


# ── Server Launch Modal ────────────────────────────────────────

class ServerLaunchScreen(ModalScreen):
    """Modal showing server launch progress."""

    def compose(self):
        yield Vertical(
            Label("Starting VITRIOL server...", classes="section-title"),
            LoadingIndicator(),
            Static("Loading model, please wait (30-60s)", id="launch-status"),
            Button("Close", id="close-launch", variant="default"),
        )

    def on_mount(self):
        self.launch()

    @work(thread=True)
    def launch(self):
        try:
            result = subprocess.run(
                ["bash", str(SCRIPT_PATH), "serve", "--detach", "--kv-mode", "offload"],
                capture_output=True, text=True, timeout=300
            )
            self.call_from_thread(self._update_status, result.returncode == 0)
        except subprocess.TimeoutExpired:
            self.call_from_thread(self._update_status, False, "Timeout")
        except Exception as e:
            self.call_from_thread(self._update_status, False, str(e))

    def _update_status(self, success: bool, msg: str = ""):
        if success:
            self.query_one("#launch-status", Static).update("✓ Server started successfully")
        else:
            self.query_one("#launch-status", Static).update(f"✗ Failed: {msg or 'check logs'}")

    def on_button_pressed(self, event: Button.Pressed):
        self.app.pop_screen()


# ── Dashboard Screen ────────────────────────────────────────────

class DashboardScreen(Screen):
    """Main dashboard with live stats and controls."""

    BINDINGS = [
        ("q", "quit", "Quit"),
        ("c", "config", "Config"),
        ("l", "launch", "Launch Server"),
        ("s", "stop", "Stop Server"),
        ("r", "refresh", "Refresh"),
    ]

    def compose(self):
        with TabbedContent(initial="tab-dash"):
            # ── Dashboard Tab ──
            with TabPane("Dashboard", id="tab-dash"):
                with Horizontal():
                    # Logo + Status column
                    with Vertical(id="left-col"):
                        yield Static(load_logo() or "VITRIOL", id="logo")
                        yield Static(id="status-msg")
                    # Stats column
                    with Vertical(id="center-col"):
                        yield Label("Live Stats", classes="section-title")
                        yield Static("Gen: --  t/s", id="stat-tps")
                        yield Static("Prompt: -- t/s", id="stat-ptps")
                        yield Static("MTP: --", id="stat-mtp")
                        yield Static("VRAM: --", id="stat-vram")
                        yield Static("Server: --", id="stat-server")
                # Bottleneck chart (placeholder)
                yield Static(
                    "Layer   FFN         Attn        PCIe\n"
                    " 0-10   ████████   ████       ████████\n"
                    "11-20   ████████   ████       ████████\n"
                    "21-30   ████████   ████       ░░░ (pin)\n"
                    "31-39   ████████   ████       ░░░ (pin)\n",
                    id="bottleneck"
                )
                # Log
                yield RichLog(id="log", highlight=True, max_lines=50)

            # ── Config Tab ──
            with TabPane("Config", id="tab-config"):
                with ScrollableContainer():
                    yield Label("VITRIOL Configuration", classes="section-title")
                    self.config_inputs = {}
                    cfg = load_config()
                    for section in ["model", "vitriol", "spec", "kv", "server"]:
                        yield Label(f"[{section}]", classes="section-header")
                        for key, label, hint in CONFIG_FIELDS:
                            if not key.startswith(f"{section}."):
                                continue
                            k = key.split(".", 1)[1]
                            val = cfg.get(key, "")
                            yield Label(label + ":", classes="field-label")
                            inp = Input(
                                value=val,
                                placeholder=hint,
                                id=f"cfg-{section}-{k}",
                                classes="field-input"
                            )
                            self.config_inputs[key] = inp
                            yield inp
                with Horizontal(classes="button-row"):
                    yield Button("Save Config", id="save-config", variant="primary")

        with Horizontal(classes="button-row"):
            yield Button("▶ Launch Server", id="btn-launch", variant="success")
            yield Button("■ Stop Server", id="btn-stop", variant="error")
            yield Button("⚙ Config", id="btn-config", variant="default")
            yield Button("Q Quit", id="btn-quit", variant="default")

    def on_mount(self):
        self.watcher = ServerLogWatcher()
        self.poll_loop()

    @work(thread=True, exit_if_already_running=True)
    def poll_loop(self):
        while True:
            self.call_from_thread(self._update)
            time.sleep(1)

    def _update(self):
        # Update VRAM
        used, total = get_vram()
        try:
            vram_w = self.query_one("#stat-vram")
            pct = int((used / total) * 100) if total > 0 else 0
            bar = "█" * (pct // 5) + "░" * (20 - pct // 5)
            vram_w.update(f"VRAM: {bar} {used:.0f}/{total:.0f} MiB ({pct}%)")
        except NoMatches:
            pass

        # Server status
        running = is_server_running()
        try:
            srv_w = self.query_one("#stat-server")
            srv_w.update(f"Server: {'▶ Running' if running else '■ Stopped'}")
        except NoMatches:
            pass

        # Update log watcher
        self.watcher.poll()

        # Update stats
        if self.watcher.last_tps > 0:
            try:
                self.query_one("#stat-tps").update(f"Gen: {self.watcher.last_tps:.1f} t/s")
            except NoMatches:
                pass
        if self.watcher.last_prompt_tps > 0:
            try:
                self.query_one("#stat-ptps").update(f"Prompt: {self.watcher.last_prompt_tps:.1f} t/s")
            except NoMatches:
                pass
        if self.watcher.last_acceptance > 0:
            try:
                self.query_one("#stat-mtp").update(f"MTP: {self.watcher.last_acceptance*100:.1f}%")
            except NoMatches:
                pass

        # Update log
        if self.watcher.new_data_available:
            try:
                log = self.query_one("#log")
                now = time.strftime("%H:%M:%S")
                if self.watcher.last_tps > 0:
                    log.write(f"[{now}] Gen: {self.watcher.last_tps:.1f} t/s")
                if self.watcher.last_acceptance > 0:
                    log.write(f"[{now}] MTP: {self.watcher.last_acceptance*100:.1f}% acc")
            except NoMatches:
                pass

    def on_button_pressed(self, event: Button.Pressed):
        bid = event.button.id
        if bid == "btn-launch":
            self.launch_server()
        elif bid == "btn-stop":
            self.stop_server()
        elif bid == "btn-config":
            self.action_config()
        elif bid == "btn-quit":
            self.app.exit()
        elif bid == "save-config":
            self._save_config()

    def _save_config(self):
        new_cfg = {}
        for key, inp in self.config_inputs.items():
            new_cfg[key] = inp.value
        save_config(new_cfg)
        try:
            self.query_one("#status-msg", Static).update("✓ Config saved")
        except NoMatches:
            pass

    def launch_server(self):
        if is_server_running():
            try:
                self.query_one("#status-msg", Static).update("Server already running")
            except NoMatches:
                pass
            return
        try:
            self.query_one("#status-msg", Static).update("Starting server...")
        except NoMatches:
            pass
        self._do_launch()

    @work(thread=True)
    def _do_launch(self):
        try:
            result = subprocess.run(
                ["bash", str(SCRIPT_PATH), "serve", "--detach"],
                capture_output=True, text=True, timeout=300
            )
            success = result.returncode == 0
            self.call_from_thread(self._launch_result, success,
                                  result.stderr.strip() or result.stdout.strip())
        except Exception as e:
            self.call_from_thread(self._launch_result, False, str(e))

    def _launch_result(self, success: bool, msg: str = ""):
        try:
            w = self.query_one("#status-msg", Static)
            if success:
                w.update("✓ Server started")
            else:
                w.update(f"✗ Launch failed: {msg[:60]}")
        except NoMatches:
            pass

    def stop_server(self):
        if stop_server():
            try:
                self.query_one("#status-msg", Static).update("✓ Server stopped")
                self.query_one("#log", RichLog).write(f"[{time.strftime('%H:%M:%S')}] Server stopped")
            except NoMatches:
                pass

    def action_config(self):
        self.push_screen(ConfigScreen())

    def action_launch(self):
        self.launch_server()

    def action_stop(self):
        self.stop_server()


# ── Main App ───────────────────────────────────────────────────

class VitriolTUI(App):
    """VITRIOL Live Dashboard with config and server control."""

    TITLE = "VITRIOL Dashboard"
    SUB_TITLE = "Live inference monitor"
    CSS = """
    Screen {
        layout: vertical;
    }
    .section-title {
        text-style: bold;
        color: $primary;
        padding: 0 1;
    }
    .section-header {
        text-style: underline;
        color: $secondary;
        padding: 1 1 0 1;
    }
    .field-label {
        padding: 0 1;
        color: $text-muted;
    }
    .field-input {
        margin: 0 1;
    }
    .button-row {
        height: auto;
        padding: 0 1;
    }
    #left-col {
        width: 1fr;
    }
    #center-col {
        width: 2fr;
    }
    #logo {
        height: auto;
        padding: 0;
    }
    #status-msg {
        color: $success;
        padding: 0 1;
    }
    #stat-tps, #stat-ptps, #stat-mtp, #stat-vram, #stat-server {
        padding: 0 1;
    }
    #bottleneck {
        border: solid $secondary;
        margin: 0 1;
    }
    #log {
        border: solid $surface;
        margin: 0 1;
        height: 1fr;
    }
    Button {
        margin: 0 1;
    }
    TabbedContent {
        height: 1fr;
    }
    """

    BINDINGS = [
        ("q", "quit", "Quit"),
    ]

    def compose(self):
        yield Header()
        yield DashboardScreen()
        yield Footer()


def main():
    app = VitriolTUI()
    app.run()


if __name__ == "__main__":
    main()
