#!/usr/bin/env bash
set -euo pipefail

# generate-alka-recipe.sh — Generate Alka recipes from GGUF model files
#
# Uses gguf-offset-resolver to extract real tensor offsets, then generates
# .alka source files for Alka compilation.
#
# Usage: ./scripts/generate-alka-recipe.sh <model.gguf> [--vessel NAME] [--output-dir DIR]

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
VITRIOL_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
RESOLVER="$VITRIOL_ROOT/alka-executor/gguf-offset-resolver"

MODEL_PATH=""
VESSEL_NAME="GPU_1070TI"
OUTPUT_DIR="$VITRIOL_ROOT/alka/generated"

while [[ $# -gt 0 ]]; do
    case "$1" in
        --vessel) VESSEL_NAME="$2"; shift 2 ;;
        --output-dir) OUTPUT_DIR="$2"; shift 2 ;;
        *) MODEL_PATH="$1"; shift ;;
    esac
done

if [ -z "$MODEL_PATH" ]; then
    echo "Usage: $0 <model.gguf> [--vessel NAME] [--output-dir DIR]"
    exit 1
fi

if [ ! -f "$RESOLVER" ]; then
    echo "Error: gguf-offset-resolver not found at $RESOLVER"
    echo "Run: make -C alka-executor"
    exit 1
fi

if [ ! -f "$MODEL_PATH" ]; then
    echo "Error: Model file not found: $MODEL_PATH"
    exit 1
fi

mkdir -p "$OUTPUT_DIR"

MODEL_NAME="$(basename "$MODEL_PATH" .gguf)"
echo "=== Generating Alka recipes for $MODEL_NAME ==="
echo "Model: $MODEL_PATH"
echo "Vessel: $VESSEL_NAME"
echo "Output: $OUTPUT_DIR"
echo ""

# ── Step 1: Extract tensor offsets ──────────────────────────────────

echo "Step 1: Parsing GGUF tensor offsets..."
RESOLVER_OUTPUT=$("$RESOLVER" "$MODEL_PATH" 2>/dev/null)

# Parse tensor list into temp file for processing
TENSOR_FILE=$(mktemp)
echo "$RESOLVER_OUTPUT" | grep "^blk\." > "$TENSOR_FILE" || true

TOTAL_TENSORS=$(wc -l < "$TENSOR_FILE")
BASE_TENSORS=$(grep -v "exps" "$TENSOR_FILE" | wc -l || echo 0)
EXPERT_TENSORS=$(grep "exps" "$TENSOR_FILE" | wc -l || echo 0)

echo "  Total tensors: $TOTAL_TENSORS"
echo "  Base tensors:  $BASE_TENSORS"
echo "  Expert tensors: $EXPERT_TENSORS"
echo ""

# ── Step 2: Generate base model recipe ─────────────────────────────

echo "Step 2: Generating base model recipe..."
BASE_RECIPE="$OUTPUT_DIR/${MODEL_NAME}_base.alka"

cat > "$BASE_RECIPE" << HEADER
// Auto-generated Alka recipe — base model loading
// Generated by generate-alka-recipe.sh on $(date -u +"%Y-%m-%dT%H:%M:%SZ")
// Model: $MODEL_NAME
//
// Loads non-expert tensors (embeddings + attention) into GPU VRAM.
// Expert tensors remain on CPU for on-demand loading via llama.cpp -ot flag.
//
// Tensors: $BASE_TENSORS base tensors loaded via sliding window.

HEADER

echo "REQUIRE vitriol_rig.alkavl;" >> "$BASE_RECIPE"
echo "" >> "$BASE_RECIPE"
echo "CLAIM ${VESSEL_NAME};" >> "$BASE_RECIPE"
echo "CLAIM NVME_SSD;" >> "$BASE_RECIPE"
echo "" >> "$BASE_RECIPE"
echo "LIMIT ${VESSEL_NAME}.THERMAL MAX 85000;" >> "$BASE_RECIPE"
echo "" >> "$BASE_RECIPE"
echo "REFRACT ${VESSEL_NAME}.VRAM 0 8GB;" >> "$BASE_RECIPE"
echo "" >> "$BASE_RECIPE"

# Generate FLOW instructions for base tensors
WINDOW_OFFSET=0
APERTURE_SIZE=$((256 * 1024 * 1024))  # 256MB
CHUNK_COUNT=0
METAPAGE=1
CURRENT_LAYER=-1

while IFS= read -r line; do
    name=$(echo "$line" | awk '{print $1}')
    layer=$(echo "$line" | awk '{print $2}')
    size=$(echo "$line" | awk '{print $4}')
    offset=$(echo "$line" | awk '{print $5}')

    # Skip expert tensors
    if echo "$name" | grep -q "exps"; then
        continue
    fi

    # New layer comment
    if [ "$layer" != "$CURRENT_LAYER" ]; then
        echo "/* Layer $layer (base) */" >> "$BASE_RECIPE"
        CURRENT_LAYER="$layer"
    fi

    # Check if we need a new window
    if [ "$WINDOW_OFFSET" -gt 0 ] && [ $((WINDOW_OFFSET + size)) -gt "$APERTURE_SIZE" ]; then
        echo "FENCE ${VESSEL_NAME}.METAPAGE == $METAPAGE;" >> "$BASE_RECIPE"
        METAPAGE=$((METAPAGE + 1))
        WINDOW_OFFSET=0
    fi

    # SHIFT if not at offset 0
    if [ "$WINDOW_OFFSET" -gt 0 ]; then
        echo "SHIFT ${VESSEL_NAME}.DATA_PLANE @ $WINDOW_OFFSET;" >> "$BASE_RECIPE"
    fi

    echo "FLOW NVME_SSD[$offset] -> ${VESSEL_NAME}.DATA_PLANE[$WINDOW_OFFSET] $size;" >> "$BASE_RECIPE"
    CHUNK_COUNT=$((CHUNK_COUNT + 1))
    WINDOW_OFFSET=$((WINDOW_OFFSET + size))
done < "$TENSOR_FILE"

if [ "$CHUNK_COUNT" -gt 0 ]; then
    echo "FENCE ${VESSEL_NAME}.METAPAGE == $METAPAGE;" >> "$BASE_RECIPE"
fi

echo "" >> "$BASE_RECIPE"
echo "SYNC L3;" >> "$BASE_RECIPE"
echo "SIGNAL INFERENCE_COMPLETE;" >> "$BASE_RECIPE"

echo "  Generated: $BASE_RECIPE ($CHUNK_COUNT chunks, $METAPAGE windows)"

# ── Step 3: Generate full stream recipe ────────────────────────────

echo "Step 3: Generating full model stream recipe..."
FULL_RECIPE="$OUTPUT_DIR/${MODEL_NAME}_full.alka"

cat > "$FULL_RECIPE" << HEADER
// Auto-generated Alka recipe — full model streaming
// Generated by generate-alka-recipe.sh on $(date -u +"%Y-%m-%dT%H:%M:%SZ")
// Model: $MODEL_NAME
//
// Loads ALL tensors (base + experts) into GPU VRAM via sliding window.
// This tests the complete NVMe→GPU DMA path.
//
// Tensors: $TOTAL_TENSORS total ($BASE_TENSORS base + $EXPERT_TENSORS expert)

HEADER

echo "REQUIRE vitriol_rig.alkavl;" >> "$FULL_RECIPE"
echo "" >> "$FULL_RECIPE"
echo "CLAIM ${VESSEL_NAME};" >> "$FULL_RECIPE"
echo "CLAIM NVME_SSD;" >> "$FULL_RECIPE"
echo "" >> "$FULL_RECIPE"
echo "LIMIT ${VESSEL_NAME}.THERMAL MAX 85000;" >> "$FULL_RECIPE"
echo "" >> "$FULL_RECIPE"
echo "REFRACT ${VESSEL_NAME}.VRAM 0 8GB;" >> "$FULL_RECIPE"
echo "" >> "$FULL_RECIPE"

# Generate FLOW instructions for ALL tensors
WINDOW_OFFSET=0
CHUNK_COUNT=0
METAPAGE=1
CURRENT_LAYER=-1

while IFS= read -r line; do
    name=$(echo "$line" | awk '{print $1}')
    layer=$(echo "$line" | awk '{print $2}')
    size=$(echo "$line" | awk '{print $4}')
    offset=$(echo "$line" | awk '{print $5}')

    # New layer comment
    if [ "$layer" != "$CURRENT_LAYER" ]; then
        echo "/* Layer $layer */" >> "$FULL_RECIPE"
        CURRENT_LAYER="$layer"
    fi

    # Check if we need a new window
    if [ "$WINDOW_OFFSET" -gt 0 ] && [ $((WINDOW_OFFSET + size)) -gt "$APERTURE_SIZE" ]; then
        echo "FENCE ${VESSEL_NAME}.METAPAGE == $METAPAGE;" >> "$FULL_RECIPE"
        METAPAGE=$((METAPAGE + 1))
        WINDOW_OFFSET=0
    fi

    # SHIFT if not at offset 0
    if [ "$WINDOW_OFFSET" -gt 0 ]; then
        echo "SHIFT ${VESSEL_NAME}.DATA_PLANE @ $WINDOW_OFFSET;" >> "$FULL_RECIPE"
    fi

    echo "FLOW NVME_SSD[$offset] -> ${VESSEL_NAME}.DATA_PLANE[$WINDOW_OFFSET] $size;" >> "$FULL_RECIPE"
    CHUNK_COUNT=$((CHUNK_COUNT + 1))
    WINDOW_OFFSET=$((WINDOW_OFFSET + size))
done < "$TENSOR_FILE"

if [ "$CHUNK_COUNT" -gt 0 ]; then
    echo "FENCE ${VESSEL_NAME}.METAPAGE == $METAPAGE;" >> "$FULL_RECIPE"
fi

echo "" >> "$FULL_RECIPE"
echo "SYNC L3;" >> "$FULL_RECIPE"
echo "SIGNAL INFERENCE_COMPLETE;" >> "$FULL_RECIPE"

echo "  Generated: $FULL_RECIPE ($CHUNK_COUNT chunks, $METAPAGE windows)"

# ── Step 4: Compile recipes ────────────────────────────────────────

echo ""
echo "Step 4: Compiling recipes with Alka compiler..."

ALKA_BIN="${VITRIOL_ALKA_BIN:-$VITRIOL_ROOT/../alka-lang/zig-out/bin/alka}"
VIAL="$VITRIOL_ROOT/alka/vials/vitriol_rig.alkavl"

if [ ! -f "$ALKA_BIN" ]; then
    echo "  Warning: Alka compiler not found at $ALKA_BIN"
    echo "  Skipping compilation. Run manually:"
    echo "    $ALKA_BIN $BASE_RECIPE $VIAL"
    echo "    $ALKA_BIN $FULL_RECIPE $VIAL"
else
    echo "  Compiling base model recipe..."
    "$ALKA_BIN" "$BASE_RECIPE" "$VIAL" 2>&1 | sed 's/^/    /'

    echo ""
    echo "  Compiling full model recipe..."
    "$ALKA_BIN" "$FULL_RECIPE" "$VIAL" 2>&1 | sed 's/^/    /'
fi

# ── Step 5: Summary ────────────────────────────────────────────────

echo ""
echo "=== Recipe Generation Complete ==="
echo ""
echo "Generated files:"
ls -la "$OUTPUT_DIR/"*.alka 2>/dev/null | awk '{print "  " $NF " (" $5 " bytes)"}'
echo ""
echo "Compiled binaries:"
ls -la "$OUTPUT_DIR/"*.alkas 2>/dev/null | awk '{print "  " $NF " (" $5 " bytes)"}'
ls -la "$OUTPUT_DIR/"*.azoth 2>/dev/null | awk '{print "  " $NF " (" $5 " bytes)"}'
echo ""
echo "To benchmark:"
echo "  ./scripts/benchmark_alka.sh"

rm -f "$TENSOR_FILE"
